### ISSUE TITLE
Database Change Request

### ISSUE THREAD

**Issue by h-sezer** [alishermatianiu/GAU-E-Participation#8]
Can we make the following changes to database?

- Add "user_id" field to student table, make it primary key and auto increment.

In order to make the back-end operations and database fetches easier.

- Add "user_id" field to category manager table, make it primary key and auto incerement.

In order to make the back-end operations and database fetches easier.

- Make "ID" field  primary key and auto incremented in "Problem" table.

This will help to create anonymous problem request. By leaving the "Student" field empty in this table, we can make problems anonymous.

**Comment by alishermatianiu** [comment]
Requested changes have been updated.
